# Generated by Django 4.1.4 on 2022-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportmsg', models.CharField(max_length=255)),
                ('instansi', models.CharField(choices=[('Basarnas', 'Basarnas'), ('BPBD', 'BPBD'), ('Damkar', 'Damkar')], max_length=10)),
            ],
        ),
    ]
